version: "3"

services:
  redis:
    image: "redis:5.0.4-stretch"
    networks:
      - gm03-network

  web:
    build:
      context: "."
    depends_on:
      - "redis"
    ports:
      - "5000:5000"
    networks:
      - gm03-network

  worker:
    build:
      context: "."
    command: celery -A app.celery_app worker --loglevel INFO --max-tasks-per-child=1
    depends_on:
      - "redis"
    networks:
      - gm03-network

networks:
  gm03-network:
    driver: bridge