version: "3"

services:
  redis:
    image: "redis:5.0.4-stretch"
    volumes:
      - "redis:/data"

  web:
    build:
      context: "."
    depends_on:
      - "redis"
    ports:
      - "5000:5000"
    restart: "unless-stopped"

  worker:
    build:
      context: "."
    command: celery -A app.celery_app worker --loglevel INFO
    depends_on:
      - "redis"
    restart: "unless-stopped"

volumes:
  redis: {}