openapi: 3.0.3
info:
  title: GM03 Validator API
  description: >-
    A RESTful API implementation to validate XML metadata against the swiss
    geographic metadata profile (ISO19139.che).
    
    
    This is implemented as asynchronous task. Multiple validation tasks can be started in parallel without having to wait for them to complete. The task status (and results when done) can be asked with the task UUID.
  version: 1.0.0
servers:
  - url: https://localhost:5000
paths:
  /api/validate:
    post:
      tags:
        - validate
      summary: Upload metadata and start validation
      description: >-
        Upload metadata in XML (following the ISO19139.che profile) and start a
        validation process. Returns the metadata uuid, title, validation status and errors if any.
      requestBody:
        description: Upload metadata and create validation task
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  items:
                    type: string
                    format: binary
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              examples:
                validation Successful:
                  value: 
                      [
                        {
                        uuid: metadata UUID,
                        title: metadata title,
                        valid: yes,
                        errors: []
                        },
                        {
                        uuid: metadata UUID,
                        title: metadata title,
                        valid: no,
                        errors: [
                          {
                          message: error 1 message,
                          location: error 1 location
                          },
                          {
                          message: error 2 message,
                          location: error 2 location
                          }
                          ]
                        }
                      ]